/**
 * Permissions test starter.
 *
 * Suggested shape (jazz-tools/testing):
 * - startLocalJazzServer(...) for an isolated server
 * - seedRows(...) to set up synthetic fixtures
 * - scopedClientForClaims(...) for request-scoped user clients
 * - expectAllowed(...) / expectDenied(...) assertions
 */
import { describe, it } from "vitest";

describe.skip("permissions", () => {
  it("add policy tests", () => {
    // Starter file generated by jazz-tools build.
  });
});
